export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const FIND_CONTACT = "FIND_CONTACT";
export const CONTACT_CHANGE = "CONTACT_CHANGE";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const ADD_PHONE = "ADD_PHONE";
export const DELETE_PHONE = "DELETE_PHONE";